adminapp/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import RedirectView
from django.urls import reverse
from adminapp import views

app_name = 'administracion'
urlpatterns = [
    path('registrar-empresa/', views.registrar_empresa, name='registrar_empresa'),
    path('empresas/', views.listar_empresas, name='listar_empresas'),
    path('empresas/actualizar/<int:empresa_id>/', views.actualizar_empresa, name='actualizar_empresa'),
    path('acceder/<int:pk>', views.acceder, name='acceder'),
    path('registro/', views.registro, name='registro'),
]

api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.urls import reverse

from rest_framework import routers

from api import views

app_name = 'api'

router = routers.DefaultRouter()

router.register('categories', views.CategoryView)
router.register('products', views.ProductView)
router.register('customers', views.CustomerView)
router.register('tipos-de-ingredientes', views.QuantityTypeView)
router.register('monedas', views.CurrencyView)
router.register('horarios-de-acceso', views.HorariosDeAccesoView)
urlpatterns = [
    path('', include(router.urls)),
    path('empresa/<str:cadena>/', views.EmpresaView.as_view(), name='empresa'),
    path('webhooks/mercado-pago/<str:cadena>/', views.MercadoPagoWebHook.as_view(), name='MercadoPagoWebHook'),

]

django_open_pos/urls.py
# -*- coding: utf-8 -*-
"""django_open_pos URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('panel-de-control/', admin.site.urls),
                  path('app/', include('mainapp.urls', 'mainapp')),
                  path('', include('website.urls', 'website')),
                  path('administracion/', include('adminapp.urls', 'administracion')),
                  path('api/', include('api.urls', 'api')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import RedirectView
from django.urls import reverse
from mainapp import views

app_name = 'mainapp'
urlpatterns = [
    # sin auth por customer
    # categorias
    path('<str:cadena>/categorias/', views.categorias_customer_view,
         name='categorias_customer_view'),
    path('<str:cadena>', views.index_customers_view,
         name='index_customers_view'),
    path('<str:cadena>/productos/<int:pk>',
         views.productos_customer_view, name='productos_customer_view'),
     path('<str:cadena>/orden/<int:pk>',
         views.orden_pagada_customer_view, name='orden_pagada_customer_view'),         
    path('<str:cadena>/carrito/', views.carrito_customer_view,
         name='carrito_customer_view'),
    path('<str:cadena>/borrar-producto/<int:pk>',
         views.eliminar_del_carrito_customer_view, name='eliminar_del_carrito_customer_view'),
    path('<str:cadena>/nueva-orden-customer/',
         views.crear_nueva_orden_customer_view, name='crear_nueva_orden_customer_view'),
     path('registro-con-exito/<str:correo_del_usuario>/', views.registro_con_exito, name='registro_con_exito'),

    # auth
    path('login/', views.LoginView.as_view(), name='login'),
    path('loutin/', views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='index'),
    # categorias
    path('categorias/', views.categorias_view, name='categorias'),
    path('agregar-categoria/', views.crear_nueva_categoria_view,
         name='crear_nueva_categoria_view'),
    path('categorias/modificar/<int:categoria_id>/',
         views.modificar_categoria_view, name='modificar_categoria_view'),
    path('categorias/eliminar/<int:categoria_id>/',
         views.eliminar_categoria_view, name='eliminar_categoria_view'),
    path('listar-categorias/', views.listar_categorias_view,
         name='listar_categorias_view'),
    # monedas
    path('agregar-moneda/', views.crear_nueva_currency_view,
         name='crear_nueva_currency_view'),
    path('monedas/modificar/<int:currency_id>/', views.modificar_currency_view,
         name='modificar_currency_view'),
    path('monedas/eliminar/<int:currency_id>/', views.eliminar_moneda_view,
         name='eliminar_moneda_view'),
    path('listar-monedas/', views.listar_monedas_view,
         name='listar_monedas_view'),
    # productos
    path('productos/<int:pk>', views.productos_view, name='productos'),
    path('productos/modificar/<int:pk>', views.modificar_producto_view,
         name='modificar_producto_view'),
    path('productos/eliminar/<int:pk>',
         views.eliminar_producto_view, name='eliminar_producto_view'),
    path('eliminar-producto/<int:pk>',
         views.eliminar_del_carrito_view, name='eliminar_del_carrito_view'),
    path('agregar-producto/', views.crear_nuevo_producto_view,
         name='crear_nuevo_producto_view'),
    path('listar-productos/', views.listar_productos_view,
         name='listar_productos_view'),
    # ordenes
    path('orden/', views.carrito_view, name='carrito'),
    path('cobrar/', views.cobrar, name='cobrar'),
    path('recibo/<int:pk>', views.GeneratePDF, name='recibo'),
    path('orden-cobrada/<int:pk>', views.orden_cobrada, name='orden_cobrada'),
    path('nueva-orden/', views.crear_nueva_orden, name='crear_nueva_orden'),
    path('detalle-de-la-orden/', views.detalle_de_la_orden,
         name='detalle_de_la_orden'),
    path('mis-ordenes/', views.mis_ordenes, name='mis_ordenes'),
    path('mis-ordenes-json/', views.mis_ordenes_json, name='mis_ordenes_json'),
    path('orden/<int:pk>', views.orden, name='orden'),
    path('orden-lista-para-entrega/<int:pk>',
         views.orden_lista_para_entrega, name='orden_lista_para_entrega'),
    path('orden-entregada/<int:pk>',
         views.orden_entregada, name='orden_entregada'),
    path('listar-ordenes/', views.listar_ordenes_view,
         name='listar_ordenes_view'),
    # Lugares
    path('agregar-lugar/', views.crear_nuevo_place_view,
         name='crear_nuevo_place_view'),
    path('listar-lugares/', views.listar_lugares_view,
         name='listar_lugares_view'),
    path('lugares/modificar/<int:place_id>',
         views.modificar_place_view, name='modificar_place_view'),
    path('lugares/eliminar/<int:place_id>',
         views.eliminar_place_view, name='eliminar_place_view'),
    # Ingredientes
    path('agregar-ingrediente/', views.crear_nuevo_ingredient_view,
         name='crear_nuevo_ingredient_view'),
    path('listar-ingredientes/', views.listar_ingredientes_view,
         name='listar_ingredientes_view'),
    path('ingredientes/modificar/<int:pk>/', views.modificar_ingredient_view,
         name='modificar_ingredient_view'),
    path('ingredientes/eliminar/<int:pk>/', views.eliminar_ingredient_view,
         name='eliminar_ingredient_view'),
    # usuarios
    path('agregar-nuevo-usuario/', views.crear_usuario, name='crear_usuario'),
    path('modificar-usuario/<int:pk>', views.modificar_usuario, name='modificar_usuario'),
    path('listar-usuarios/', views.listar_usuarios_view,
         name='listar_usuarios_view'),
    # Cantidades
    path('agregar-tipo-de-cantidad/', views.crear_nuevo_quantity_type_view,
         name='crear_nuevo_quantity_type_view'),
    path('listar-tipos-de-cantidades/', views.listar_tipos_de_cantidades_view,
         name='listar_tipos_de_cantidades_view'),
    path('tipos-de-cantidades/modificar/<int:quantity_id>/', views.modificar_quantity_type_view,
         name='modificar_quantity_type_view'),
    path('tipos-de-cantidades/eliminar/<int:quantity_id>/', views.eliminar_quantity_type_view,
         name='eliminar_quantity_type_view'),
    # Clientes
    path('listar-clientes/', views.listar_clientes_view,
         name='listar_clientes_view'),
]

adminapp/models/cuenta.py
# -*- coding: utf-8 -*-
from datetime import timedelta
from datetime import date

from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.contrib.admin import ModelAdmin
from django.db import models
from django.contrib.auth.models import User
from mainapp.models import DatosDeControlMixin


class Cuenta(DatosDeControlMixin):
    usuario = models.OneToOneField(User, on_delete=models.DO_NOTHING, null=True, blank=True,
                                   related_name='relacion_cuenta_de_usuario', default=None,
                                   help_text='Fk a usuario para conocer el usuario que propietario de la cuenta')

    cantidad_empresas = models.PositiveIntegerField(default=5, null=False)

    # cuenta
    vencimiento = models.DateField(null=True)
    cantidad_movimientos = models.PositiveIntegerField(default=500, null=True)

    # factura
    timbres_restantes = models.PositiveIntegerField(default=0, null=False)
    timbres_usados = models.PositiveIntegerField(default=0, null=False)

    # administracion
    invitado_por = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, null=True, blank=True, related_name='invitado_por',
    )

    @property
    def vigente(self):
        return self.vencimiento >= date.today()

    def __str__(self):
        return str(self.usuario.username)


class CuentaAdmin(ModelAdmin):
    search_fields = ['user__username', 'usuario__email']


# Funcion para crear la cuenta despues de crear un usuario
def crear_cuenta(sender, instance, created, **kwargs):
    if not created:
        return
    cuenta = Cuenta()
    cuenta.usuario = instance
    cuenta.vencimiento = date.today() + timedelta(days=30)
    cuenta.timbres_restantes = 5
    cuenta.timbres_usados = 0
    cuenta.save()


# Conectar funcion para crear cuenta despues de crear un usuario
post_save.connect(crear_cuenta, sender=get_user_model())

adminapp/models/empresa.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import date

import uuid
import os

from django.utils.text import slugify
from django.core.validators import RegexValidator
from django.contrib.admin import ModelAdmin
from django.db import models
from django.contrib.auth.models import User
from mainapp.models import DatosDeControlMixin


def eliminar_espacios_blancos(valor):
    return valor.strip().replace(" ", "")


def upload_to(instance, filename):
    filename, ext = os.path.splitext(filename)
    return 'administracion/{}/logo/{}{}'.format(
        instance.rfc,
        uuid.uuid4(),
        ext
    )

class CiudadadPermitida(DatosDeControlMixin):
    description = models.CharField(
        max_length=100, null=False, blank=False, help_text='Ciudada permitida Description'
    )

    def __str__(self):
        return "{0}-{1}".format(self.pk, self.description)


class CiudadadPermitidaAdmin(ModelAdmin):
    search_fields = ['description'] 

class HorarioAcceso(DatosDeControlMixin):    
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    def __str__(self):
        hora_inicio_str = self.hora_inicio.strftime("%I:%M %p")
        hora_fin_str = self.hora_fin.strftime("%I:%M %p")
        return f"{self.pk} - Hora de inicio: {hora_inicio_str} - Hora de cierre: {hora_fin_str}"
    
class HorarioAccesoAdmin(ModelAdmin):
    search_fields = ['hora_inicio'] 

class Empresa(DatosDeControlMixin):
    rfc = models.CharField(
        max_length=13, blank=True, null=True, unique=True,
        validators=[
            RegexValidator(
                regex='^([A-Z&Ññ]{3,4}|[A-Z][AEIOU][A-Z]{2})\d{2}((01|03|05|07|08|10|12)(0[1-9]|[12]\d|3[01])|02(0[1-9]|[12]\d)|(04|06|09|11)(0[1-9]|[12]\d|30))([A-Z0-9]{2}[0-9A])?$',
                message='El formato del RFC no es correcto. Ej. XAXX010101000'
            )
        ]
    )
    razon_social = models.CharField(
        max_length=250, blank=False, null=False, db_index=True, verbose_name='Razón social *'
    )
    nombre_comercial = models.CharField(
        max_length=200, blank=False, null=False, db_index=True, verbose_name='Nombre comercial *'
    )
    # Facturacion
    cer = models.FileField(
        upload_to='administracion/efirma', null=True, blank=True)
    key = models.FileField(
        upload_to='administracion/efirma', null=True, blank=True)
    contrasena = models.CharField(max_length=20, null=True, blank=True)
    correo_electronico = models.EmailField(blank=False, null=False)
    logo = models.ImageField(
        upload_to=upload_to,
        null=True,
        blank=True,
        help_text='Su imagen se re-dimensionara (200px~100px)',
    )

    cuenta = models.ForeignKey('adminapp.Cuenta', on_delete=models.DO_NOTHING, null=True, blank=True,
                               related_name='relacion_cuenta_a_empresa',
                               help_text='Fk a cuenta de usuario a la que pertenece la empresa')

    ciudades_permitidas = models.ManyToManyField(
        CiudadadPermitida,
        blank=True,
        related_name='relacion_ciudades_permitidas_a_empresa',
        help_text='Ciudades permitidas a las que pertenece la empresa'
    )
    usuarios = models.ManyToManyField(User)
    sdk_private = models.CharField(max_length=100, unique=True, null=True, blank=True, default=None)
    sdk_public = models.CharField(max_length=100, unique=True, null=True, blank=True, default=None)
    horario_de_acceso = models.ForeignKey(HorarioAcceso, null=True, blank=True, default=None, on_delete=models.CASCADE,
                                       related_name='horarios_acceso', help_text="Horario de acceso al portal del cliente.")

    nombre_para_pagos = models.CharField(
        max_length=200, blank=False, null=True, db_index=True, verbose_name='Nombre con el que accederán los clientes de esta empresa*'
    )

    @property
    def vigente(self):
        return self.cuenta.vencimiento >= date.today()

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        self.rfc = self.rfc.upper()
        self.correo_electronico = self.correo_electronico.lower()
        self.nombre_para_pagos = eliminar_espacios_blancos(
            self.nombre_para_pagos)
        super(Empresa, self).save(*args, **kwargs)


class EmpresaAdmin(ModelAdmin):
    search_fields = ['rfc', 'razon_social']


class PaymentWithMercadoPago(DatosDeControlMixin):
    action = models.CharField(max_length=255,null=True, blank=True)
    api_version = models.CharField(max_length=10,null=True, blank=True)
    data = models.JSONField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    data_id = models.BigIntegerField(unique=True,null=True, blank=True)
    live_mode = models.BooleanField(default=False, null=True, blank=True)
    payment_type = models.CharField(max_length=255, null=True, blank=True)
    payment_id = models.CharField(max_length=255, null=True, blank=True)
    user_id = models.CharField(max_length=255, help_text='Es lo mismo que collector_id y preference_id' , null=False, blank=False)
    coupon_code = models.CharField(max_length=255, null=True, blank=True)
    coupon_labels = models.CharField(max_length=255, null=True, blank=True)
    date_of_expiration = models.DateTimeField(null=True, blank=True)
    expiration_date_from = models.DateTimeField(null=True, blank=True)
    expiration_date_to = models.DateTimeField(null=True, blank=True)
    expires = models.BooleanField(default=False, null=True, blank=True)
    external_reference = models.CharField(max_length=255, null=True, blank=True)
    init_point = models.URLField(max_length=200, null=True, blank=True)
    internal_metadata = models.JSONField(null=True, blank=True)
    items = models.JSONField(null=True, blank=True)
    nueva_orden = models.JSONField(null=True, blank=True)
    pagado = models.BooleanField(default=False)

    def __str__(self):
        return f"Payment ID: {self.payment_id}, User ID:"

class PaymentWithMercadoPagoAdmin(ModelAdmin):
    search_fields = ['user_id', 'coupon_code', 'external_reference', 'data_id']

adminapp/templates/adminapp/listar_empresas.html
{% extends 'mvcapp/base.html' %}
{% load humanize %}
{% load static %}
{% block titulo %}Empresas{% endblock %}
{% block navegacion %}Empresas{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            {% if empresas %}
                <div class="col-sm-12 right">
                    <a href="{% url 'administracion:registrar_empresa' %}" class="btn btn-primary btn-round">Agregar una
                        nueva empresa
                    </a>
                </div>
                <br><br>
                {% for empresa in empresas %}
                    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column"
                            {% if empresa.vigente %}
                         onclick="window.location='{% url 'administracion:acceder' empresa.pk %}'"
                            {% endif %}
                    >
                        <div class="card bg-light d-flex flex-fill">
                            <div class="card-header text-muted border-bottom-0">

                            </div>
                            <div class="card-body pt-0">
                                <div class="row">
                                    <div class="col-7">
                                        <h4><b>{{ empresa.nombre_comercial }}</b></h4>
                                        Vencimiento: {{ empresa.cuenta.vencimiento }}
                                        {% if not empresa.vigente %}
                                            - <b style="color: red">VENCIDA</b>
                                        {% endif %}
                                    </div>

                                    {% if empresa.logo %}
                                        <div class="col-5 text-center">
                                            <img alt="{{ empresa.nombre_comercial }}" src="{{ empresa.logo.url }}"
                                                 style="width: 128px; height: 128px;"
                                                 class="img-fluid mb-2">
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-12 col-sm-6 col-md-6 d-flex align-items-stretch flex-column">
                    <span>No existen empresas registradas.</span>
                    <a href="{% url 'administracion:registrar_empresa' %}" class="btn btn-primary btn-round">Agregar una
                        nueva empresa
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}


adminapp/templates/adminapp/registrar_empresa.html
{% extends 'mvcapp/base.html' %}

{% block titulo %}Agregar Empresa{% endblock %}
{% load humanize %}
{% block navegacion %}Agregar Empresa{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Agregar Empresa</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group">
                            <label for="correo_electronico">Correo electronico</label>
                            <input type="email" class="form-control" id="correo_electronico" name="correo_electronico"
                                   placeholder="ejemplo@example.com" required>
                        </div>
                        <div class="form-group">
                            <label for="rfc">RFC</label>
                            <input type="text" class="form-control" id="rfc" name="rfc"
                                   placeholder="XXX010101AX1" oninput="this.value = this.value.toUpperCase()">
                            <small class="text-muted">*Este campo es opcional</small>
                            {% if form.rfc.errors %}
                                   <small style="color: red;">
                                       {% for error in form.rfc.errors %}
                                           {{ error }}
                                       {% endfor %}
                                   </small>
                            {% endif %}                                   
                        </div>
                        <div class="form-group">
                            <label for="razon_social">Razon social</label>
                            <input type="text" class="form-control" id="razon_social" name="razon_social"
                                   placeholder="Empresa de ejemplo S.A. de C.V.">
                            <small class="text-muted">*Este campo es opcional</small>
                        </div>
                        <div class="form-group">
                            <label for="nombre_comercial">Nombre comercial</label>
                            <input type="text" class="form-control" id="nombre_comercial" name="nombre_comercial"
                                   placeholder="Hot Dogs el buen sabor" required>
                                {% if form.nombre_comercial.errors %}
                                   <small style="color: red;">
                                       {% for error in form.nombre_comercial.errors %}
                                           {{ error }}
                                       {% endfor %}
                                   </small>
                               {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="nombre_para_pagos">Nombre que recibira tu portal de pagos</label>
                            <input type="text" class="form-control" id="nombre_para_pagos" name="nombre_para_pagos"
                                   placeholder="hotdogselbuensabor">
                                {% if form.nombre_para_pagos.errors %}
                                   <small style="color: red;">
                                       {% for error in form.nombre_para_pagos.errors %}
                                           {{ error }}
                                       {% endfor %}
                                   </small>
                               {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="logo">Logotipo</label>
                            <input type="file" id="logo" name="logo">
                            {% if form.logo.errors %}
                                <small style="color: red;">
                                    {% for error in form.logo.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </small>
                            {% endif %}
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Regresar</a>
                        <button type="submit" class="btn btn-primary float-right">Agregar empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            var txtRFC = $('#id_rfc');
            txtRFC.attr('style', 'text-transform: uppercase');
            var re = /^([A-Z&Ññ]{3,4}|[A-Z][AEIOU][A-Z]{2})\d{2}((01|03|05|07|08|10|12)(0[1-9]|[12]\d|3[01])|02(0[1-9]|[12]\d)|(04|06|09|11)(0[1-9]|[12]\d|30))([A-Z0-9]{2}[0-9A])?$/;
            txtRFC.change(function (e) {
                val = $(this).val().toUpperCase();
                if (!re.test(val)) {
                    $(this).addClass('invalid');
                    $('#btnSubmit').attr('disabled', 'true');
                } else {
                    $(this).removeClass('invalid ');
                    $('#btnSubmit').removeAttr('disabled');
                }
            });
        });
    </script>
{% endblock %}


adminapp/templates/adminapp/registro.html
{% extends 'adminapp/base.html' %}

{% block title %}Registro{% endblock %}

{% block form %}
    <p class="login-box-msg">
        <br>
        <b>Registrar usuario</b>
    </p>

    <form method="post" enctype="multipart/form-data" accept-charset="UTF-8">
        {% csrf_token %}
        <div class="form-group" data-validate="email requerido">
            {% if form.email.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ form.email.errors }}</div>{% endif %}
            <label class="control-label" for="id_correo_electronico">Correo Electrónico</label>
            <input type="email" name="email" title="" required="" class="form-control" id="id_correo_electronico"
                   placeholder="{{ form.email.label }}" value="{{ form.email.value|default:'' }}">
        </div>
        <div class="form-group" data-validate="first_name requerido">
            {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ form.first_name.errors }}</div>{% endif %}
            <label class="control-label" for="id_nombre">Nombres</label>
            <input type="text" name="first_name" title="" required="" id="id_nombre" maxlength="30" class="form-control"
                   placeholder="Ej. Luis Leocadio">
        </div>
        <div class="form-group" data-validate="last_name requerido">
            {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ form.last_name.errors }}</div>{% endif %}
            <label class="control-label" for="id_apellido">Apellidos</label>
            <input type="text" name="last_name" title="" required="" id="id_apellido" maxlength="30"
                   placeholder="Ej. Iturrios Medina"
                   class="form-control">
        </div>
        <div class="form-group" data-validate="password1 requerido">
            {% if form.password1.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ form.password1.errors }}</div>{% endif %}
            <label class="control-label" for="id_contrasena1">Contraseña</label>
            <input type="password" name="password1" title="Ingrese una contraseña segura" required=""
                   id="id_contrasena1" class="form-control" placeholder="Escriba su contraseña">

        </div>
        <div class="form-group" data-validate="password2 requerido">
            {% if form.password2.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ form.password2.errors }}</div>{% endif %}
            <label class="control-label" for="id_contrasena2">Repetir contraseña </label>
            <input type="password" name="password2" title="Ingrese nuevamente su contraseña" required=""
                   id="id_contrasena2" placeholder="Escriba de nuevo su contraseña" class="form-control">
            <div class="help-block">Ingrese nuevamente su contraseña</div>
        </div>
        <div class="form-group">
            <div class="checkbox">
                <label for="id_terminos">
                    <input type="checkbox" name="terminos" required="" class="" id="id_terminos"> Acepto los <a
                        target="_blank" href="#">términos y condiciones del servicio</a>
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block btn-flat">Registrarme</button>
    </form>
    <br>
    <a href="{% url 'mainapp:login' %}">Iniciar sesión </a><br>
    <div class="modal modal-danger fade in" id="modal-danger" style="padding-right: 16px;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span>Error</span>
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title">Error.</h4>
                </div>
                <div class="modal-body">
                    <p>{{ form.non_field_errors }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btn-okay" class="btn btn-outline" data-dismiss="modal">Okay</button>
                </div>
            </div>
        </div>
        <!-- /.modal-dialog -->
    </div>
{% endblock %}

{% block script %}
    {% if form.non_field_errors %}
        <script>
            $("#modal-danger").modal('show');
            $(document).on('keypress', function (e) {
                if (event.keyCode == 13) {
                    $("#modal-danger").modal('hide');
                }
            });
        </script>
    {% endif %}
{% endblock %}