api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.urls import reverse

from rest_framework import routers

from api import views

app_name = 'api'

router = routers.DefaultRouter()

router.register('categories', views.CategoryView)
router.register('products', views.ProductView)
router.register('customers', views.CustomerView)
router.register('tipos-de-ingredientes', views.QuantityTypeView)
router.register('monedas', views.CurrencyView)
router.register('horarios-de-acceso', views.HorariosDeAccesoView)
urlpatterns = [
    path('', include(router.urls)),
    path('empresa/<str:cadena>/', views.EmpresaView.as_view(), name='empresa'),
    path('webhooks/mercado-pago/<str:cadena>/', views.MercadoPagoWebHook.as_view(), name='MercadoPagoWebHook'),

]

django_open_pos/urls.py
# -*- coding: utf-8 -*-
"""django_open_pos URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('panel-de-control/', admin.site.urls),
                  path('app/', include('mainapp.urls', 'mainapp')),
                  path('', include('website.urls', 'website')),
                  path('administracion/', include('adminapp.urls', 'administracion')),
                  path('api/', include('api.urls', 'api')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import RedirectView
from django.urls import reverse
from mainapp import views

app_name = 'mainapp'
urlpatterns = [
    # sin auth por customer
    # categorias
    path('<str:cadena>/categorias/', views.categorias_customer_view,
         name='categorias_customer_view'),
    path('<str:cadena>', views.index_customers_view,
         name='index_customers_view'),
    path('<str:cadena>/productos/<int:pk>',
         views.productos_customer_view, name='productos_customer_view'),
     path('<str:cadena>/orden/<int:pk>',
         views.orden_pagada_customer_view, name='orden_pagada_customer_view'),         
    path('<str:cadena>/carrito/', views.carrito_customer_view,
         name='carrito_customer_view'),
    path('<str:cadena>/borrar-producto/<int:pk>',
         views.eliminar_del_carrito_customer_view, name='eliminar_del_carrito_customer_view'),
    path('<str:cadena>/nueva-orden-customer/',
         views.crear_nueva_orden_customer_view, name='crear_nueva_orden_customer_view'),
     path('registro-con-exito/<str:correo_del_usuario>/', views.registro_con_exito, name='registro_con_exito'),

    # auth
    path('login/', views.LoginView.as_view(), name='login'),
    path('loutin/', views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='index'),
    # categorias
    path('categorias/', views.categorias_view, name='categorias'),
    path('agregar-categoria/', views.crear_nueva_categoria_view,
         name='crear_nueva_categoria_view'),
    path('categorias/modificar/<int:categoria_id>/',
         views.modificar_categoria_view, name='modificar_categoria_view'),
    path('categorias/eliminar/<int:categoria_id>/',
         views.eliminar_categoria_view, name='eliminar_categoria_view'),
    path('listar-categorias/', views.listar_categorias_view,
         name='listar_categorias_view'),
    # monedas
    path('agregar-moneda/', views.crear_nueva_currency_view,
         name='crear_nueva_currency_view'),
    path('monedas/modificar/<int:currency_id>/', views.modificar_currency_view,
         name='modificar_currency_view'),
    path('monedas/eliminar/<int:currency_id>/', views.eliminar_moneda_view,
         name='eliminar_moneda_view'),
    path('listar-monedas/', views.listar_monedas_view,
         name='listar_monedas_view'),
    # productos
    path('productos/<int:pk>', views.productos_view, name='productos'),
    path('productos/modificar/<int:pk>', views.modificar_producto_view,
         name='modificar_producto_view'),
    path('productos/eliminar/<int:pk>',
         views.eliminar_producto_view, name='eliminar_producto_view'),
    path('eliminar-producto/<int:pk>',
         views.eliminar_del_carrito_view, name='eliminar_del_carrito_view'),
    path('agregar-producto/', views.crear_nuevo_producto_view,
         name='crear_nuevo_producto_view'),
    path('listar-productos/', views.listar_productos_view,
         name='listar_productos_view'),
    # ordenes
    path('orden/', views.carrito_view, name='carrito'),
    path('cobrar/', views.cobrar, name='cobrar'),
    path('recibo/<int:pk>', views.GeneratePDF, name='recibo'),
    path('orden-cobrada/<int:pk>', views.orden_cobrada, name='orden_cobrada'),
    path('nueva-orden/', views.crear_nueva_orden, name='crear_nueva_orden'),
    path('detalle-de-la-orden/', views.detalle_de_la_orden,
         name='detalle_de_la_orden'),
    path('mis-ordenes/', views.mis_ordenes, name='mis_ordenes'),
    path('mis-ordenes-json/', views.mis_ordenes_json, name='mis_ordenes_json'),
    path('orden/<int:pk>', views.orden, name='orden'),
    path('orden-lista-para-entrega/<int:pk>',
         views.orden_lista_para_entrega, name='orden_lista_para_entrega'),
    path('orden-entregada/<int:pk>',
         views.orden_entregada, name='orden_entregada'),
    path('listar-ordenes/', views.listar_ordenes_view,
         name='listar_ordenes_view'),
    # Lugares
    path('agregar-lugar/', views.crear_nuevo_place_view,
         name='crear_nuevo_place_view'),
    path('listar-lugares/', views.listar_lugares_view,
         name='listar_lugares_view'),
    path('lugares/modificar/<int:place_id>',
         views.modificar_place_view, name='modificar_place_view'),
    path('lugares/eliminar/<int:place_id>',
         views.eliminar_place_view, name='eliminar_place_view'),
    # Ingredientes
    path('agregar-ingrediente/', views.crear_nuevo_ingredient_view,
         name='crear_nuevo_ingredient_view'),
    path('listar-ingredientes/', views.listar_ingredientes_view,
         name='listar_ingredientes_view'),
    path('ingredientes/modificar/<int:pk>/', views.modificar_ingredient_view,
         name='modificar_ingredient_view'),
    path('ingredientes/eliminar/<int:pk>/', views.eliminar_ingredient_view,
         name='eliminar_ingredient_view'),
    # usuarios
    path('agregar-nuevo-usuario/', views.crear_usuario, name='crear_usuario'),
    path('modificar-usuario/<int:pk>', views.modificar_usuario, name='modificar_usuario'),
    path('listar-usuarios/', views.listar_usuarios_view,
         name='listar_usuarios_view'),
    # Cantidades
    path('agregar-tipo-de-cantidad/', views.crear_nuevo_quantity_type_view,
         name='crear_nuevo_quantity_type_view'),
    path('listar-tipos-de-cantidades/', views.listar_tipos_de_cantidades_view,
         name='listar_tipos_de_cantidades_view'),
    path('tipos-de-cantidades/modificar/<int:quantity_id>/', views.modificar_quantity_type_view,
         name='modificar_quantity_type_view'),
    path('tipos-de-cantidades/eliminar/<int:quantity_id>/', views.eliminar_quantity_type_view,
         name='eliminar_quantity_type_view'),
    # Clientes
    path('listar-clientes/', views.listar_clientes_view,
         name='listar_clientes_view'),
]

mainapp/models/receipt.py
# -*- coding: utf-8 -*-
from django.db import models

from mainapp.models import DatosDeControlMixin


class Currency(DatosDeControlMixin):
    """
    La tabla contiene la información de las categorías de solicitudes registradas en el sistema.
    """
    description = models.CharField(max_length=100, null=False, blank=False, help_text='Currency type Description')
    symbol = models.CharField(max_length=100, null=False, blank=False, help_text='Currency symbol')
    empresa = models.ForeignKey('adminapp.Empresa', null=False, blank=False, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{0}-{1}".format(self.pk, self.description)

mainapp/views/categorias.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from datetime import datetime, timedelta
from django.utils import timezone

from mainapp.models import Category
from mainapp.models import Product
from adminapp.models import Empresa
from mainapp import views
from mainapp import forms
from .index import validar_horario


@login_required()
def listar_categorias_view(request):
    if not 'empresa' in request.session:
        messages.add_message(request, messages.ERROR,
                             'Tiene que acceder con una empresa.')
        return redirect('administracion:listar_empresas')
    else:
        empresa = Empresa.objects.get(pk=request.session['empresa'])
        if not empresa.vigente:
            messages.add_message(request, messages.WARNING,
                                 'La empresa presenta un adeudo, comuniquese con el administrador del portal')
            return redirect('administracion:listar_empresas')

    categorias = Category.objects.filter(eliminado=False, empresa=empresa)
    return render(request, 'mvcapp/categorias/listar_categorias.html',
                  {'categorias': categorias, 'empresa_pk': empresa.pk})


@login_required()
def categorias_view(request):
    if not 'empresa' in request.session:
        messages.add_message(request, messages.ERROR,
                             'Tiene que acceder con una empresa.')
        return redirect('administracion:listar_empresas')
    else:
        empresa = Empresa.objects.get(pk=request.session['empresa'])
        if not empresa.vigente:
            messages.add_message(request, messages.WARNING,
                                 'La empresa presenta un adeudo, comuniquese con el administrador del portal')
            return redirect('administracion:listar_empresas')
    categorias = Category.objects.filter(eliminado=False, empresa=empresa)
    return render(request, 'mvcapp/categorias/categorias.html',
                  {'categorias': categorias, 'empresa_pk': empresa.pk})


@login_required()
def crear_nueva_categoria_view(request):
    if not 'empresa' in request.session:
        messages.add_message(request, messages.ERROR,
                             'Tiene que acceder con una empresa.')
        return redirect('administracion:listar_empresas')
    else:
        empresa = Empresa.objects.get(pk=request.session['empresa'])
        if not empresa.vigente:
            messages.add_message(request, messages.WARNING,
                                 'La empresa presenta un adeudo, comuniquese con el administrador del portal')
            return redirect('administracion:listar_empresas')

    if request.method == 'POST':

        form = forms.form_agregar_categoria(request.POST, request.FILES)
        if form.is_valid():
            categoria = form.save(commit=False)
            categoria.empresa = empresa
            categoria.save()
            messages.add_message(request, messages.INFO,
                                 'Categoria agregada con exito')
            return redirect('mainapp:listar_categorias_view')
        else:
            return render(request, 'mvcapp/categorias/crear_categoria.html', {'form': form, 'empresa_pk': empresa.pk})

    else:
        form = forms.form_agregar_categoria()
        form.fields['description'].label = 'Descripción de la categoria'
        form.fields['clave'].label = 'Clave de la categoria'
        form.fields['image'].label = 'Imagen de la categoria'

    return render(request, 'mvcapp/categorias/crear_categoria.html', {'form': form, 'empresa_pk': empresa.pk})


@login_required()
def modificar_categoria_view(request, categoria_id=None):
    if not 'empresa' in request.session:
        messages.add_message(request, messages.ERROR,
                             'Tiene que acceder con una empresa.')
        return redirect('administracion:listar_empresas')
    else:
        empresa = Empresa.objects.get(pk=request.session['empresa'])
        if not empresa.vigente:
            messages.add_message(request, messages.WARNING,
                                 'La empresa presenta un adeudo, comuniquese con el administrador del portal')
            return redirect('administracion:listar_empresas')

    if request.method == 'POST':
        form = forms.form_modificar_categoria(request.POST, request.FILES)
        if form.is_valid():
            if categoria_id:
                categoria = get_object_or_404(
                    Category, pk=categoria_id, empresa=empresa)
                # Verificar si se proporcionó una nueva imagen en el formulario
                if 'image' in form.changed_data:
                    categoria.image = form.cleaned_data['image']
                categoria.description = form.cleaned_data['description']
                categoria.clave = form.cleaned_data['clave']
                categoria.save()
                messages.add_message(request, messages.INFO,
                                     'Categoría modificada con éxito')
                return redirect('mainapp:listar_categorias_view')
            else:
                messages.add_message(request, messages.WARNING,
                                     'Metodo no permitido')
                return redirect('mainapp:listar_categorias_view')
        else:
            return render(request, 'mvcapp/categorias/modificar_categoria.html', {'form': form, 'empresa_pk': empresa.pk})
    else:
        if categoria_id:
            categoria = get_object_or_404(
                Category, pk=categoria_id, empresa=empresa)
            # Asignar la imagen existente al formulario
            form = forms.form_modificar_categoria(
                instance=categoria, initial={'image': categoria.image})
            form.fields['description'].label = 'Descripción de la categoria'
            form.fields['clave'].label = 'Clave de la categoria'
            form.fields['image'].label = 'Imagen de la categoria'
        else:
            form = forms.form_modificar_categoria()

    return render(request, 'mvcapp/categorias/modificar_categoria.html', {'form': form, 'empresa_pk': empresa.pk})


@login_required()
def eliminar_categoria_view(request, categoria_id):
    if not 'empresa' in request.session:
        messages.add_message(request, messages.ERROR,
                             'Tiene que acceder con una empresa.')
        return redirect('administracion:listar_empresas')
    else:
        empresa = Empresa.objects.get(pk=request.session['empresa'])
        if not empresa.vigente:
            messages.add_message(request, messages.WARNING,
                                 'La empresa presenta un adeudo, comuniquese con el administrador del portal')
            return redirect('administracion:listar_empresas')

    categoria = get_object_or_404(Category, pk=categoria_id, empresa=empresa)

    if request.method == 'POST':
        categoria.delete()
        messages.add_message(request, messages.INFO,
                             'Categoría eliminada con éxito')
        return redirect('mainapp:listar_categorias_view')

    else:
        messages.add_message(request, messages.WARNING, 'Metodo no permitido')
        return redirect('mainapp:listar_categorias_view')

# sin auth para customer


def categorias_customer_view(request, cadena):
    empresa = get_object_or_404(Empresa, nombre_para_pagos=cadena)
    if empresa.horario_de_acceso:
        hora_actual = timezone.now()
        hora_actual_hermosillo = hora_actual - timedelta(hours=7)
        hora_actual = hora_actual_hermosillo.time()
        hora_inicio = empresa.horario_de_acceso.hora_inicio
        hora_fin = empresa.horario_de_acceso.hora_fin
        if not validar_horario(hora_inicio, hora_fin, hora_actual):    
            messages.add_message(request, messages.WARNING, 'La empresa está fuera de horario')
            return redirect('website:fuera_de_horario', empresa.pk)
    if not empresa.vigente:
        messages.add_message(request, messages.WARNING,
                             'La empresa presenta adeudo y no tiene disponible la sección de pedidos')
        return redirect('administracion:registro')

    categorias = Category.objects.filter(eliminado=False, empresa=empresa)
    return render(request, 'mvcapp/categorias/categorias_customers.html',
                  {'categorias': categorias, 'cadena': cadena, 'empresa': empresa})

mainapp/templates/mvcapp/lugares/crear_lugar.html
{% extends 'mvcapp/base.html' %}

{% block titulo %}Agregar Sucursal{% endblock %}
{% load humanize %}
{% block navegacion %}Agregar Sucursal{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Agregar Sucursal</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group">
                            <label for="description">Nombre de la Sucursal</label>
                            <input type="text" class="form-control" id="description" name="description"
                                   placeholder="Matriz" required>
                        </div>
                        <div class="form-group">
                            <label for="direction">Dirección de la Sucursal</label>
                            <textarea class="form-control" id="direction" name="direction" rows="2"
                                      placeholder="Calle 5 y callejon madero  #321" required></textarea>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Regresar</a>
                        <button type="submit" class="btn btn-primary float-right">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mvcapp/lugares/listar_lugares.html
{% extends 'mvcapp/base.html' %}

{% block titulo %}Sucursales{% endblock %}
{% load humanize %}
{% block navegacion %}Sucursales{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Regresar</a>
                    <a class="btn btn-primary btn-round float-right" href="{% url 'mainapp:crear_nuevo_place_view' %}">Agregar
                        nueva Sucursal</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped dataTable dtr-inline"
                                       role="grid" aria-describedby="example1_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1"
                                            colspan="1">
                                            Nombre
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1"
                                            colspan="1">
                                            Dirección
                                        </th>
                                        <th>Eliminar</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for lugar in lugares %}
                                        <tr class="odd">
                                            <td class="dtr-control sorting_1">
                                                <a href="{% url 'mainapp:modificar_place_view' lugar.pk %}">{{ lugar.description }}</a></td>
                                            <td class="dtr-control sorting_1">{{ lugar.direction }}</td>
                                            <td class="dtr-control sorting_1">
                                                <form method="post" action="{% url 'mainapp:eliminar_place_view' lugar.pk %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-link text-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar esta sucursal?')">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "print",]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
{% endblock %}

mainapp/templates/mvcapp/lugares/modificar_lugar.html
{% extends 'mvcapp/base.html' %}

{% block titulo %}Modificar Sucursal{% endblock %}
{% load humanize %}
{% block navegacion %}Modificar Sucursal{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Modificar Sucursal</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% if field.field.widget.input_type != 'hidden' %}
                                    {{ field }}
                                {% else %}
                                    {{ field.as_hidden }}
                                {% endif %}
                                {% if field.field.help_text %}
                                    <small class="form-text text-muted">{{ field.field.help_text }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Regresar</a>
                        <button type="submit" class="btn btn-primary float-right">Guardar cambios</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}